"project_id": "645230"
"api_token": "c5c60aefb48eaf141c9685f38ab01cdb5c4be33d65105aa6b80088b72de3499376a4dda47567d677"
"base_path": "."
"base_url": "https://api.crowdin.com"
"preserve_hierarchy": true

"files": [
  {
    "source": "FriishProduce/Strings/*.resx",                                       #source files filter
    "translation": "strings/%original_file_name%"                                   #where translations are stored
  }
]
