"project_id": "645230"
"api_token": "3913abc79b6d6d801462c128de34578164c96d9d0bfab7cd18ee73ea4118bf5e68dae5e1175f29da"
"base_path": "."
"base_url": "https://api.crowdin.com"
"preserve_hierarchy": true

"files": [
  {
    "source": "FriishProduce/Strings/**",                                             #source files filter
    "translation": "%original_path%/%file_name%.%locale%.%file_extension%",           #where translations are stored
    "languages_mapping": {
        "locale": {
            "af": "af",
            "am": "am",
            "an": "an",
            "ar": "ar",
            "ast": "ast",
            "az": "az",
            "ber": "ber",
            "be": "be",
            "bg": "bg",
            "bn": "bn",
            "bs": "bs",
            "ca": "ca",
            "ckb": "ckb",
            "co": "co",
            "cs": "cs",
            "da": "da",
            "de": "de",
            "el": "el",
            "en": "en",
            "et": "et",
            "eu": "eu",
            "fa": "fa",
            "fi": "fi",
            "fr": "fr",
            "ga-IE": "ga",
            "gl": "gl",
            "he": "he",
            "hr": "hr",
            "hu": "hu",
            "hy-AM": "hy",
            "id": "id",
            "is": "is",
            "it": "it",
            "ja": "ja",
            "ka": "ka",
            "kab": "kab",
            "kk": "kk",
            "ko": "ko",
            "ku": "ku",
            "lt": "lt",
            "lv": "lv",
            "ms": "ms",
            "nb": "nb",
            "nl": "nl",
            "oc": "oc",
            "om": "om",
            "pl": "pl",
            "ro": "ro",
            "ru": "ru",
            "sk": "sk",
            "sl": "sl",
            "sq": "sq",
            "sr": "sr",
            "tg": "tg",
            "th": "th",
            "ti": "ti",
            "tr": "tr",
            "uk": "uk",
            "uz": "uz",
            "vi": "vi",
            "es-ES": "es",
            "pa-IN": "pa",
            "sv-SE": "sv",
            "pt-PT": "pt",
            "zh-CN": "zh-Hans",
            "zh-TW": "zh-Hant"
         }
      }
  }
]
