"project_id": "645230"
"api_token": "3913abc79b6d6d801462c128de34578164c96d9d0bfab7cd18ee73ea4118bf5e68dae5e1175f29da"
"base_path": "."
"base_url": "https://api.crowdin.com"
"preserve_hierarchy": true

"files": [
  {
    "source": "FriishProduce/Strings/*.resx",                                       #source files filter
    "translation": "FriishProduce/Strings/%osx_locale%/%original_file_name%"        #where translations are stored
  }
]
