//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FriishProduce.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sys")]
        public string UI_Language {
            get {
                return ((string)(this["UI_Language"]));
            }
            set {
                this["UI_Language"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ImageInterpolation {
            get {
                return ((int)(this["ImageInterpolation"]));
            }
            set {
                this["ImageInterpolation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoLibRetro {
            get {
                return ((bool)(this["AutoLibRetro"]));
            }
            set {
                this["AutoLibRetro"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Default_N64_FixBrightness {
            get {
                return ((bool)(this["Default_N64_FixBrightness"]));
            }
            set {
                this["Default_N64_FixBrightness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Default_N64_FixCrashes {
            get {
                return ((bool)(this["Default_N64_FixCrashes"]));
            }
            set {
                this["Default_N64_FixCrashes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Default_N64_ExtendedRAM {
            get {
                return ((bool)(this["Default_N64_ExtendedRAM"]));
            }
            set {
                this["Default_N64_ExtendedRAM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Default_N64_AllocateROM {
            get {
                return ((bool)(this["Default_N64_AllocateROM"]));
            }
            set {
                this["Default_N64_AllocateROM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Default_N64_ROMC0 {
            get {
                return ((bool)(this["Default_N64_ROMC0"]));
            }
            set {
                this["Default_N64_ROMC0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DoNotShow_000 {
            get {
                return ((bool)(this["DoNotShow_000"]));
            }
            set {
                this["DoNotShow_000"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ImageFitAspectRatio {
            get {
                return ((bool)(this["ImageFitAspectRatio"]));
            }
            set {
                this["ImageFitAspectRatio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DoNotShow_Welcome {
            get {
                return ((bool)(this["DoNotShow_Welcome"]));
            }
            set {
                this["DoNotShow_Welcome"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SD")]
        public string Default_Forwarders_FilesStorage {
            get {
                return ((string)(this["Default_Forwarders_FilesStorage"]));
            }
            set {
                this["Default_Forwarders_FilesStorage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Wii")]
        public string Default_Forwarders_Mode {
            get {
                return ((string)(this["Default_Forwarders_Mode"]));
            }
            set {
                this["Default_Forwarders_Mode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("VC2")]
        public string Default_NEO_BIOS {
            get {
                return ((string)(this["Default_NEO_BIOS"]));
            }
            set {
                this["Default_NEO_BIOS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string Default_SEGA_6B {
            get {
                return ((string)(this["Default_SEGA_6B"]));
            }
            set {
                this["Default_SEGA_6B"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Default_NES_Palette {
            get {
                return ((int)(this["Default_NES_Palette"]));
            }
            set {
                this["Default_NES_Palette"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Default_NES_UsePaletteForBanner {
            get {
                return ((bool)(this["Default_NES_UsePaletteForBanner"]));
            }
            set {
                this["Default_NES_UsePaletteForBanner"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string Default_SEGA_SRAM {
            get {
                return ((string)(this["Default_SEGA_SRAM"]));
            }
            set {
                this["Default_SEGA_SRAM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("87")]
        public string Default_SEGA_Brightness {
            get {
                return ((string)(this["Default_SEGA_Brightness"]));
            }
            set {
                this["Default_SEGA_Brightness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("us")]
        public string Default_SEGA_Region {
            get {
                return ((string)(this["Default_SEGA_Region"]));
            }
            set {
                this["Default_SEGA_Region"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string Default_PCE_Europe {
            get {
                return ((string)(this["Default_PCE_Europe"]));
            }
            set {
                this["Default_PCE_Europe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string Default_PCE_SuperGrafx {
            get {
                return ((string)(this["Default_PCE_SuperGrafx"]));
            }
            set {
                this["Default_PCE_SuperGrafx"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public string Default_PCE_Pad {
            get {
                return ((string)(this["Default_PCE_Pad"]));
            }
            set {
                this["Default_PCE_Pad"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string Default_PCE_YOffset {
            get {
                return ((string)(this["Default_PCE_YOffset"]));
            }
            set {
                this["Default_PCE_YOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string Default_PCE_SpriteLimit {
            get {
                return ((string)(this["Default_PCE_SpriteLimit"]));
            }
            set {
                this["Default_PCE_SpriteLimit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string Default_PCE_HideOverscan {
            get {
                return ((string)(this["Default_PCE_HideOverscan"]));
            }
            set {
                this["Default_PCE_HideOverscan"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string Default_PCE_BGRaster {
            get {
                return ((string)(this["Default_PCE_BGRaster"]));
            }
            set {
                this["Default_PCE_BGRaster"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string Default_PCE_BackupRAM {
            get {
                return ((string)(this["Default_PCE_BackupRAM"]));
            }
            set {
                this["Default_PCE_BackupRAM"] = value;
            }
        }
    }
}
