//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FriishProduce {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FriishProduce.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to |All files (*.*)|*.*.
        /// </summary>
        internal static string browse_AllFiles {
            get {
                return ResourceManager.GetString("browse_AllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nintendo 64 ROM files (*.n64, *.v64, *.z64)|*.n64;*.v64;*.z64.
        /// </summary>
        internal static string browseROM_n64 {
            get {
                return ResourceManager.GetString("browseROM_n64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nintendo Entertainment System/Famicom ROM files (*.nes)|*.nes.
        /// </summary>
        internal static string browseROM_nes {
            get {
                return ResourceManager.GetString("browseROM_nes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Super Nintendo Entertainment System/Super Famicom ROM files (*.sfc;*.smc)|*.sfc;*.smc.
        /// </summary>
        internal static string browseROM_snes {
            get {
                return ResourceManager.GetString("browseROM_snes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Really delete this WAD?.
        /// </summary>
        internal static string deleteWAD {
            get {
                return ResourceManager.GetString("deleteWAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Halt.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An undefined exception occured during the exportation process.
        ///
        ///Message: {0}.
        /// </summary>
        internal static string errorInject {
            get {
                return ResourceManager.GetString("errorInject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done..
        /// </summary>
        internal static string finished {
            get {
                return ResourceManager.GetString("finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to beta 1.
        /// </summary>
        internal static string version {
            get {
                return ResourceManager.GetString("version", resourceCulture);
            }
        }
    }
}
