//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FriishProduce.Options {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class ADOBEFLASH : global::System.Configuration.ApplicationSettingsBase {
        
        private static ADOBEFLASH defaultInstance = ((ADOBEFLASH)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ADOBEFLASH())));
        
        public static ADOBEFLASH Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("on")]
        public string mouse {
            get {
                return ((string)(this["mouse"]));
            }
            set {
                this["mouse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("on")]
        public string qwerty_keyboard {
            get {
                return ((string)(this["qwerty_keyboard"]));
            }
            set {
                this["qwerty_keyboard"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("high")]
        public string quality {
            get {
                return ((string)(this["quality"]));
            }
            set {
                this["quality"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("on")]
        public string shared_object_capability {
            get {
                return ((string)(this["shared_object_capability"]));
            }
            set {
                this["shared_object_capability"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1024")]
        public string vff_cache_size {
            get {
                return ((string)(this["vff_cache_size"]));
            }
            set {
                this["vff_cache_size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("on")]
        public string vff_sync_on_write {
            get {
                return ((string)(this["vff_sync_on_write"]));
            }
            set {
                this["vff_sync_on_write"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("yes")]
        public string hbm_no_save {
            get {
                return ((string)(this["hbm_no_save"]));
            }
            set {
                this["hbm_no_save"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("none")]
        public string strap_reminder {
            get {
                return ((string)(this["strap_reminder"]));
            }
            set {
                this["strap_reminder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2048")]
        public string persistent_storage_total {
            get {
                return ((string)(this["persistent_storage_total"]));
            }
            set {
                this["persistent_storage_total"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1024")]
        public string persistent_storage_per_movie {
            get {
                return ((string)(this["persistent_storage_per_movie"]));
            }
            set {
                this["persistent_storage_per_movie"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public string update_frame_rate {
            get {
                return ((string)(this["update_frame_rate"]));
            }
            set {
                this["update_frame_rate"] = value;
            }
        }
    }
}
