//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FriishProduce.Options {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class FORWARDER : global::System.Configuration.ApplicationSettingsBase {
        
        private static FORWARDER defaultInstance = ((FORWARDER)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new FORWARDER())));
        
        public static FORWARDER Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sd")]
        public string root_storage_device {
            get {
                return ((string)(this["root_storage_device"]));
            }
            set {
                this["root_storage_device"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("wii")]
        public string nand_loader {
            get {
                return ((string)(this["nand_loader"]));
            }
            set {
                this["nand_loader"] = value;
            }
        }
    }
}
