//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FriishProduce.Options {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class VC_N64 : global::System.Configuration.ApplicationSettingsBase {
        
        private static VC_N64 defaultInstance = ((VC_N64)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new VC_N64())));
        
        public static VC_N64 Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string romc_type {
            get {
                return ((string)(this["romc_type"]));
            }
            set {
                this["romc_type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string patch_fixbrightness {
            get {
                return ((string)(this["patch_fixbrightness"]));
            }
            set {
                this["patch_fixbrightness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public string patch_fixcrashes {
            get {
                return ((string)(this["patch_fixcrashes"]));
            }
            set {
                this["patch_fixcrashes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public string patch_expandedram {
            get {
                return ((string)(this["patch_expandedram"]));
            }
            set {
                this["patch_expandedram"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string patch_autosizerom {
            get {
                return ((string)(this["patch_autosizerom"]));
            }
            set {
                this["patch_autosizerom"] = value;
            }
        }
    }
}
