//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FriishProduce.Options {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class VC_NEO : global::System.Configuration.ApplicationSettingsBase {
        
        private static VC_NEO defaultInstance = ((VC_NEO)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new VC_NEO())));
        
        public static VC_NEO Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("VC2")]
        public string bios {
            get {
                return ((string)(this["bios"]));
            }
            set {
                this["bios"] = value;
            }
        }
    }
}
