//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FriishProduce.Options {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    public sealed partial class VC_PCE : global::System.Configuration.ApplicationSettingsBase {
        
        private static VC_PCE defaultInstance = ((VC_PCE)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new VC_PCE())));
        
        public static VC_PCE Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string BACKUPRAM {
            get {
                return ((string)(this["BACKUPRAM"]));
            }
            set {
                this["BACKUPRAM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public string PADBUTTON {
            get {
                return ((string)(this["PADBUTTON"]));
            }
            set {
                this["PADBUTTON"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string EUROPE {
            get {
                return ((string)(this["EUROPE"]));
            }
            set {
                this["EUROPE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string SGENABLE {
            get {
                return ((string)(this["SGENABLE"]));
            }
            set {
                this["SGENABLE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string HIDEOVERSCAN {
            get {
                return ((string)(this["HIDEOVERSCAN"]));
            }
            set {
                this["HIDEOVERSCAN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string YOFFSET {
            get {
                return ((string)(this["YOFFSET"]));
            }
            set {
                this["YOFFSET"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string RASTER {
            get {
                return ((string)(this["RASTER"]));
            }
            set {
                this["RASTER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string SPRLINE {
            get {
                return ((string)(this["SPRLINE"]));
            }
            set {
                this["SPRLINE"] = value;
            }
        }
    }
}
