//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FriishProduce.Options {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class VC_SNES : global::System.Configuration.ApplicationSettingsBase {
        
        private static VC_SNES defaultInstance = ((VC_SNES)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new VC_SNES())));
        
        public static VC_SNES Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public string patch_volume {
            get {
                return ((string)(this["patch_volume"]));
            }
            set {
                this["patch_volume"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public string patch_nodark {
            get {
                return ((string)(this["patch_nodark"]));
            }
            set {
                this["patch_nodark"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public string patch_nocc {
            get {
                return ((string)(this["patch_nocc"]));
            }
            set {
                this["patch_nocc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public string patch_nosuspend {
            get {
                return ((string)(this["patch_nosuspend"]));
            }
            set {
                this["patch_nosuspend"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public string patch_nosave {
            get {
                return ((string)(this["patch_nosave"]));
            }
            set {
                this["patch_nosave"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public string patch_widescreen {
            get {
                return ((string)(this["patch_widescreen"]));
            }
            set {
                this["patch_widescreen"] = value;
            }
        }
    }
}
