site_name: "FriishProduce"
site_description: "World's first WYSYWYG injector for Wii Virtual Console"
repo_url: https://github.com/CatmanFan/FriishProduce
repo_name: GitHub

nav:
  - Home: index.md
  - Tutorial: tutorial.md
  - FAQ: faq.md
  - Translate: translate.md
  - About: about.md

theme:
# Bootstrap theme settings
# ---------------------------------------------
  # name: bootstrap
  # logo: img/logo.png

# Material theme settings
# ---------------------------------------------
  name: material
  custom_dir: docs/
  logo: assets/images/logo.png
  favicon: assets/images/favicon.ico
  features:
    - navigation.tabs
    - toc.integrate
  palette:
    # Palette toggle for light mode
    # - scheme: default
    #   primary: white
    #   accent: light blue
    #   toggle:
    #     icon: material/brightness-7
    #     name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: custom
      accent: blue
    #   toggle:
    #     icon: material/brightness-4
    #     name: Switch to light mode

extra_css:
  - assets/extra.css

plugins:
  - glightbox:
       touchNavigation: true
       loop: false
       effect: zoom
       slide_effect: slide

  - i18n:
      docs_structure: folder
      fallback_to_default: true
      languages:
        - locale: en
          name: English
          build: true
          default: true
          admonition_translations:
            note: ""
            info: ""
            warning: ""
            danger: ""

        - locale: fr
          name: Français
          build: true
          admonition_translations:
            note: ""
            info: ""
            warning: ""
            danger: ""
          site_description: "Premier injecteur GUI pour la Console virtuelle de Wii"
          nav_translations:
            Home: Accueil
            Tutorial: Tutoriel
            Translate: Traduire
            About: À propos

        - locale: es
          name: Español
          build: true
          admonition_translations:
            note: ""
            info: ""
            warning: ""
            danger: ""
          nav_translations:
            Home: Pagina principal
            Tutorial: Tutorial
            FAQ: Preguntas frecuentes
            Translate: Traducir
            About: Acerca de

        - locale: ja
          name: 日本語
          build: false
          admonition_translations:
            note: ""
            info: ""
            note: ""
            warning: ""
          nav_translations:
            Home: ホームページ
            Tutorial: 使い方
            Translate: 翻訳
            FAQ: よくあるご質問
            About: ついて

extra:
  # The language switcher values are stored here.
  # ---------------------------------------------
  alternate:
    - name: English
      link: ""
      lang: en

    - name: Français
      link: fr
      lang: fr

    - name: Español
      link: es
      lang: es

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption