site_name: FriishProduce
repo_url: https://github.com/CatmanFan/FriishProduce
repo_name: CatmanFan/FriishProduce

nav:
  - Home: index.md
  - Tutorial: tutorial.md
  - FAQ: faq.md
  - About: about.md

theme:
# Bootstrap theme settings
# ---------------------------------------------
  name: bootstrap
  logo: img/logo.png

# Material theme settings
# ---------------------------------------------
  # name: material
  # logo: img/logo.png
  # palette:
    # # Palette toggle for light mode
    # - scheme: default
      # primary: white
      # accent: blue
      # toggle:
        # icon: material/brightness-7
        # name: Switch to dark mode

    # # Palette toggle for dark mode
    # - scheme: slate
      # primary: black
      # accent: light blue
      # toggle:
        # icon: material/brightness-4
        # name: Switch to light mode

extra_css:
  - assets/extra.css

plugins:
  - i18n:
      docs_structure: folder
      default_language: en
      fallback_to_default: true
      languages:
        - locale: en
          build: true
          default: true

        - locale: fr
          build: true
          nav_translations:
            Home: Accueil
            Tutorial: Tutoriel
            About: À propos

        - locale: ja
          build: true
          nav_translations:
            Home: ホームページ
            Tutorial: 使い方
            About: ついて

extra:
  # The language switcher values are stored here.
  # ---------------------------------------------
  alternate:
    - name: English
      link: ""
      lang: en

    - name: Français
      link: fr
      lang: fr

    - name: 日本語
      link: ja
      lang: ja

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences