site_name: "FriishProduce"
site_description: "World's first WYSYWYG injector for Wii Virtual Console"
repo_url: https://github.com/CatmanFan/FriishProduce
repo_name: GitHub

nav:
  - Home: index.md
  - Tutorial: tutorial.md
  - FAQ: faq.md
  - About: about.md

theme:
# Bootstrap theme settings
# ---------------------------------------------
  # name: bootstrap
  # logo: img/logo.png

# Material theme settings
# ---------------------------------------------
  name: material
  logo: img/logo.png
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: blue grey
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra_css:
  - assets/extra.css

plugins:
  - i18n:
      docs_structure: folder
      fallback_to_default: true
      languages:
        - locale: en
          name: English
          build: true
          default: true

        - locale: fr
          name: Français
          build: true
          site_description: "Premier injecteur GUI pour la Console virtuelle de Wii"
          nav_translations:
            Home: Accueil
            Tutorial: Tutoriel
            About: À propos
          admonition_translations:
            warning: Attention

        - locale: ja
          name: 日本語
          build: true
          site_description: "WiiVC用初のGUIインジェクター"
          nav_translations:
            Home: ホームページ
            Tutorial: 使い方
            About: ついて

        - locale: "null"
          name: Add translation
          build: false
          fixed_link: translate-wiki.md

extra:
  # The language switcher values are stored here.
  # ---------------------------------------------
  alternate:
    - name: English
      link: ""
      lang: en

    - name: Français
      link: fr
      lang: fr

    - name: 日本語
      link: ja
      lang: ja

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences