//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Options_VCN64 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Options_VCN64() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FriishProduce.Strings.Options_VCN64", typeof(Options_VCN64).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patches.
        /// </summary>
        internal static string gbox008_Text {
            get {
                return ResourceManager.GetString("gbox008.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen brightness fix.
        /// </summary>
        internal static string n64000_Text {
            get {
                return ResourceManager.GetString("n64000.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crashes fix.
        /// </summary>
        internal static string n64001_Text {
            get {
                return ResourceManager.GetString("n64001.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extended RAM patch.
        /// </summary>
        internal static string n64002_Text {
            get {
                return ResourceManager.GetString("n64002.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allocate for ROM size.
        /// </summary>
        internal static string n64003_Text {
            get {
                return ResourceManager.GetString("n64003.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROM compression type.
        /// </summary>
        internal static string n64004_Text {
            get {
                return ResourceManager.GetString("n64004.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROMC Type 0.
        /// </summary>
        internal static string ROMCType_Items {
            get {
                return ResourceManager.GetString("ROMCType.Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROMC Type 1.
        /// </summary>
        internal static string ROMCType_Items1 {
            get {
                return ResourceManager.GetString("ROMCType.Items1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please note that these options may not work for all base WADs..
        /// </summary>
        internal static string x009_Text {
            get {
                return ResourceManager.GetString("x009.Text", resourceCulture);
            }
        }
    }
}
