//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FriishProduce.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Options_VCNES {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Options_VCNES() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FriishProduce.Strings.Options_VCNES", typeof(Options_VCNES).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Also use palette for banner image.
        /// </summary>
        internal static string checkBox1_Text {
            get {
                return ResourceManager.GetString("checkBox1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen.
        /// </summary>
        internal static string groupBox1_Text {
            get {
                return ResourceManager.GetString("groupBox1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palette:.
        /// </summary>
        internal static string label1_Text {
            get {
                return ResourceManager.GetString("label1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restored.
        /// </summary>
        internal static string PaletteList_Items1 {
            get {
                return ResourceManager.GetString("PaletteList.Items1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3DS Virtual Console.
        /// </summary>
        internal static string PaletteList_Items2 {
            get {
                return ResourceManager.GetString("PaletteList.Items2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NES Classic (FBX).
        /// </summary>
        internal static string PaletteList_Items3 {
            get {
                return ResourceManager.GetString("PaletteList.Items3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NES Remix U.
        /// </summary>
        internal static string PaletteList_Items4 {
            get {
                return ResourceManager.GetString("PaletteList.Items4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nestopia YUV.
        /// </summary>
        internal static string PaletteList_Items5 {
            get {
                return ResourceManager.GetString("PaletteList.Items5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nestopia RGB.
        /// </summary>
        internal static string PaletteList_Items6 {
            get {
                return ResourceManager.GetString("PaletteList.Items6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FCEUX.
        /// </summary>
        internal static string PaletteList_Items7 {
            get {
                return ResourceManager.GetString("PaletteList.Items7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wavebeam (FBX).
        /// </summary>
        internal static string PaletteList_Items8 {
            get {
                return ResourceManager.GetString("PaletteList.Items8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Composite Direct (FBX).
        /// </summary>
        internal static string PaletteList_Items9 {
            get {
                return ResourceManager.GetString("PaletteList.Items9", resourceCulture);
            }
        }
    }
}
