//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FriishProduce.Strings.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FriishProduce.
        /// </summary>
        public static string _AppTitle {
            get {
                return ResourceManager.GetString("_AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Translation Author(s)].
        /// </summary>
        public static string _TranslationAuthor {
            get {
                return ResourceManager.GetString("_TranslationAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KB.
        /// </summary>
        public static string Abbreviation_Kilobytes {
            get {
                return ResourceManager.GetString("Abbreviation_Kilobytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MB.
        /// </summary>
        public static string Abbreviation_Megabytes {
            get {
                return ResourceManager.GetString("Abbreviation_Megabytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About {0}.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author(s): {0}.
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Cancel.
        /// </summary>
        public static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;OK.
        /// </summary>
        public static string Button_OK {
            get {
                return ResourceManager.GetString("Button_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string ByDefault {
            get {
                return ResourceManager.GetString("ByDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to connect to the Internet..
        /// </summary>
        public static string Error000 {
            get {
                return ResourceManager.GetString("Error000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to generate image. This may be due to an issue with GDI+..
        /// </summary>
        public static string Error001 {
            get {
                return ResourceManager.GetString("Error001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to replace data..
        /// </summary>
        public static string Error002 {
            get {
                return ResourceManager.GetString("Error002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ROM provided is too large (over {0} {1} in size)..
        /// </summary>
        public static string Error003 {
            get {
                return ResourceManager.GetString("Error003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to modify the following content options:
        ///{0}
        ///Injection will continue as intended..
        /// </summary>
        public static string Error004 {
            get {
                return ResourceManager.GetString("Error004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application needed ({0}) was not found in the resources\tools subdirectory..
        /// </summary>
        public static string Error005 {
            get {
                return ResourceManager.GetString("Error005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to export to WAD..
        /// </summary>
        public static string Error006 {
            get {
                return ResourceManager.GetString("Error006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a valid emanual contents folder.
        ///
        ///Injection will continue as intended..
        /// </summary>
        public static string Error007 {
            get {
                return ResourceManager.GetString("Error007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to |All files (*.*)|*.*.
        /// </summary>
        public static string Filter_All {
            get {
                return ResourceManager.GetString("Filter_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disc Images (*.cue, *.iso, *.chd)|*.cue;*.iso;*.chd|  Cue Sheet files (*.cue)|*.cue|  ISO images (*.iso)|*.iso|  Compressed Hunks of Data (*.chd)|*.chd.
        /// </summary>
        public static string Filter_Disc {
            get {
                return ResourceManager.GetString("Filter_Disc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images (*.bmp, *.jpg, *.jpeg, *.png)|*.bmp;*.jpg;*.jpeg;*.png|  Bitmap (*.bmp)|*.bmp|  JPEG (*.jpg, *.jpeg)|*.jpg;*.jpeg|  PNG (*.png)|*.png.
        /// </summary>
        public static string Filter_Img {
            get {
                return ResourceManager.GetString("Filter_Img", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patch files (*.bps, *.ips, *.xdelta)|*.bps;*.ips;*.xdelta.
        /// </summary>
        public static string Filter_Patch {
            get {
                return ResourceManager.GetString("Filter_Patch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSX1/MSX2 ROM files (*.rom, *.mx1, *.mx2)|*.rom;*.mx1;*.mx2.
        /// </summary>
        public static string Filter_ROM_MSX {
            get {
                return ResourceManager.GetString("Filter_ROM_MSX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nintendo 64 ROM files (*.n64, *.v64, *.z64)|*.n64;*.v64;*.z64.
        /// </summary>
        public static string Filter_ROM_N64 {
            get {
                return ResourceManager.GetString("Filter_ROM_N64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NES/Famicom ROM files (*.nes)|*.nes.
        /// </summary>
        public static string Filter_ROM_NES {
            get {
                return ResourceManager.GetString("Filter_ROM_NES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TurboGrafx-16/PC Engine ROM files (*.pce)|*.pce.
        /// </summary>
        public static string Filter_ROM_PCE {
            get {
                return ResourceManager.GetString("Filter_ROM_PCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mega Drive/Genesis ROM files (*.bin, *.gen, *.md)|*.bin;*.gen;*.md.
        /// </summary>
        public static string Filter_ROM_SMDGEN {
            get {
                return ResourceManager.GetString("Filter_ROM_SMDGEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master System ROM files (*.sms)|*.sms.
        /// </summary>
        public static string Filter_ROM_SMS {
            get {
                return ResourceManager.GetString("Filter_ROM_SMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SNES/Super Famicom ROM files (*.sfc, *.smc)|*.sfc;*.smc.
        /// </summary>
        public static string Filter_ROM_SNES {
            get {
                return ResourceManager.GetString("Filter_ROM_SNES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SWF files (*.swf)|*.swf.
        /// </summary>
        public static string Filter_SWF {
            get {
                return ResourceManager.GetString("Filter_SWF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wii Channels (*.wad)|*.wad.
        /// </summary>
        public static string Filter_WAD {
            get {
                return ResourceManager.GetString("Filter_WAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZIP archives (*.zip)|*.zip.
        /// </summary>
        public static string Filter_ZIP {
            get {
                return ResourceManager.GetString("Filter_ZIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Injection method options.
        /// </summary>
        public static string InjectionMethodOptions {
            get {
                return ResourceManager.GetString("InjectionMethodOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low
        ///High
        ///Bilinear
        ///Bicubic
        ///Nearest Neighbor
        ///High Quality Bilinear
        ///High Quality Bicubic.
        /// </summary>
        public static string List_ImageInterpolation {
            get {
                return ResourceManager.GetString("List_ImageInterpolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen brightness fix
        ///Crashes fix
        ///Extended ROM patch
        ///Allocation for ROM size.
        /// </summary>
        public static string List_N64Options {
            get {
                return ResourceManager.GetString("List_N64Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An application restart is needed in order for changes to take effect.
        ///Restart now?.
        /// </summary>
        public static string Message000 {
            get {
                return ResourceManager.GetString("Message000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard unsaved changes to &quot;{0}&quot;?.
        /// </summary>
        public static string Message001 {
            get {
                return ResourceManager.GetString("Message001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard all unsaved changes?.
        /// </summary>
        public static string Message002 {
            get {
                return ResourceManager.GetString("Message002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully exported to WAD:
        ///{0}.
        /// </summary>
        public static string Message003 {
            get {
                return ResourceManager.GetString("Message003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve all LibRetro data for the selected software. Some fields may need to be filled manually..
        /// </summary>
        public static string Message004 {
            get {
                return ResourceManager.GetString("Message004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected WAD ({0}) is not valid.
        ///Either it is not yet available in the database, or it is of the incorrect console..
        /// </summary>
        public static string Message005 {
            get {
                return ResourceManager.GetString("Message005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commodore 64.
        /// </summary>
        public static string Platform_C64 {
            get {
                return ResourceManager.GetString("Platform_C64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flash.
        /// </summary>
        public static string Platform_Flash {
            get {
                return ResourceManager.GetString("Platform_Flash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSX/MSX2.
        /// </summary>
        public static string Platform_MSX {
            get {
                return ResourceManager.GetString("Platform_MSX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nintendo 64.
        /// </summary>
        public static string Platform_N64 {
            get {
                return ResourceManager.GetString("Platform_N64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEO-GEO.
        /// </summary>
        public static string Platform_NeoGeo {
            get {
                return ResourceManager.GetString("Platform_NeoGeo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NES/Famicom.
        /// </summary>
        public static string Platform_NES {
            get {
                return ResourceManager.GetString("Platform_NES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TurboGrafx-16/PC Engine.
        /// </summary>
        public static string Platform_PCE {
            get {
                return ResourceManager.GetString("Platform_PCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TurboGrafx-16 CD/PC Engine CD.
        /// </summary>
        public static string Platform_PCECD {
            get {
                return ResourceManager.GetString("Platform_PCECD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mega Drive/Genesis.
        /// </summary>
        public static string Platform_SMDGEN {
            get {
                return ResourceManager.GetString("Platform_SMDGEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master System.
        /// </summary>
        public static string Platform_SMS {
            get {
                return ResourceManager.GetString("Platform_SMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SNES/Super Famicom.
        /// </summary>
        public static string Platform_SNES {
            get {
                return ResourceManager.GetString("Platform_SNES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nintendo.
        /// </summary>
        public static string PlatformGroup_0 {
            get {
                return ResourceManager.GetString("PlatformGroup_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEGA.
        /// </summary>
        public static string PlatformGroup_1 {
            get {
                return ResourceManager.GetString("PlatformGroup_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEC.
        /// </summary>
        public static string PlatformGroup_2 {
            get {
                return ResourceManager.GetString("PlatformGroup_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SNK.
        /// </summary>
        public static string PlatformGroup_3 {
            get {
                return ResourceManager.GetString("PlatformGroup_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commodore.
        /// </summary>
        public static string PlatformGroup_4 {
            get {
                return ResourceManager.GetString("PlatformGroup_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft.
        /// </summary>
        public static string PlatformGroup_5 {
            get {
                return ResourceManager.GetString("PlatformGroup_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Macromedia/Adobe.
        /// </summary>
        public static string PlatformGroup_6 {
            get {
                return ResourceManager.GetString("PlatformGroup_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Project.
        /// </summary>
        public static string ProjectType {
            get {
                return ResourceManager.GetString("ProjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Europe.
        /// </summary>
        public static string Region_E {
            get {
                return ResourceManager.GetString("Region_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japan.
        /// </summary>
        public static string Region_J {
            get {
                return ResourceManager.GetString("Region_J", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korea.
        /// </summary>
        public static string Region_K {
            get {
                return ResourceManager.GetString("Region_K", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USA.
        /// </summary>
        public static string Region_U {
            get {
                return ResourceManager.GetString("Region_U", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untitled {0} WAD.
        /// </summary>
        public static string Untitled {
            get {
                return ResourceManager.GetString("Untitled", resourceCulture);
            }
        }
    }
}
