# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2

    - name: Setup MSBuild v1
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet v2
      uses: NuGet/setup-nuget@v2
  
    - name: Setup MSBuild v1.1
      uses: microsoft/setup-msbuild@v1.1

    - name: Restore Packages
      run: nuget restore FriishProduce.sln

    - name: Build solution
      run: msbuild FriishProduce\FriishProduce.csproj -t:publish -property:Configuration=Release

    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT