name: Publish docs via GitHub Pages

on:
  push:
    branches: [ "main" ]
    paths:
      - docs/**
      - .github/workflows/mkdocs.yml
  pull_request:
    branches: [ "main" ]
    paths:
      - docs/**
      - .github/workflows/mkdocs.yml

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          
      - name: Setup Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 

      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      - name: Install dependencies
        run: pip install -r requirements.txt
        working-directory: docs/

      - name: Deploy GitHub Pages website
        run: mkdocs gh-deploy --force
        working-directory: docs/