name: virustotal

on:
  workflow_call:

jobs:
  virustotal:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
    - uses: actions/checkout@v4

    - name: VirusTotal Scan
      uses: crazy-max/ghaction-virustotal@v4
      with:
        vt_api_key: ${{ secrets.VT_API_KEY }}
        update_release_body: true
        files: |
        .exe$